### ISSUE TITLE
missing supervisor-encoder.conf 

### ISSUE THREAD

**Issue by allegfede** [YoannQueret/ODR-EncoderManager#19]
Hello everybody.

In installation instruction the line:
ln -s /home/odr/ODR-EncoderManager/supervisor-encoder.conf /etc/supervisor/conf.d/odr-encoder.conf

refers at a file i cannot find in the project folder (supervisor-encoder.conf ) .... was that renamed?

cannot start encoder manager 'cause the symbolik link was inconsistent ... i suppose (Error during supervisor process check: Can not retreive supervisor process: <ProtocolError for user:pass@127.0.0.1:8900/RPC2: 401 Unauthorized>
Use configuration file config.json)

PS: if i already have a section (main supervisor interface):
[inet_http_server]
port = 8001
username = xxxxx ; Auth username
password = xxxxxx ; Auth password

should i also config a section  for odr-encodeManager?
[inet_http_server]
port = 8900
username = xxxxxx ; Auth username
password = xxxx ; Auth password

**Comment by YoannQueret** [comment]
Hi
The file /home/odr/ODR-EncoderManager/supervisor-encoder.conf is created when you setup your first encoder.
It's not a problem to create a sym link on unexisting file.

I think you can't start the process because it can't connect to the supervisor API.

Please tune the supervisor configuration with the "supervisor_xmlrpc" parameter: "http://user:pass@127.0.0.1:8900/RPC2" in the config.json file.
user, pass and port (8900) need to be the same in config.json than supervisor configuration file in "inet_http_server" section

Yoann

**Comment by allegfede** [comment]
thanks for your help.
Now encoder manager results running in the supervisor web gui.

Now I only need to discover why the manager at port 8080 says crededentials are incorrect 🥲
